package com.example.geoalarm

import android.content.Context
import android.location.Location
import com.example.geoalarm.network.AccommodationItem
import com.example.geoalarm.network.JobItem
import com.example.geoalarm.network.LocationCoordinate
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

object GeofenceHelper {

    const val DEFAULT_MAX_ACCURACY_METERS = 15f
    const val PINPOINT_PERIMETER_BUFFER_METERS = 5f // Pin-to-pin 5m high accuracy boundary tolerance

    /**
     * Standard Ray-Casting algorithm to determine if a point is inside a polygon.
     */
    fun isPointInPolygon(lat: Double, lng: Double, points: List<LocationCoordinate>): Boolean {
        if (points.size < 3) return false
        var inside = false
        var j = points.size - 1
        for (i in points.indices) {
            val pi = points[i]
            val pj = points[j]
            if ((pi.longitude > lng) != (pj.longitude > lng) &&
                lat < (pj.latitude - pi.latitude) * (lng - pi.longitude) / (pj.longitude - pi.longitude) + pi.latitude
            ) {
                inside = !inside
            }
            j = i
        }
        return inside
    }

    /**
     * Checks whether a GPS location reading has acceptable accuracy.
     * Rejects erratic cell-tower / WiFi multipath jumps (e.g. 40m - 100m error)
     * when phone is resting indoors.
     */
    fun isLocationAccurate(location: Location?, maxAccuracyMeters: Float = DEFAULT_MAX_ACCURACY_METERS): Boolean {
        if (location == null) return false
        if (!location.hasAccuracy()) return true
        return location.accuracy <= maxAccuracyMeters
    }

    /**
     * Inspects whether a GPS location reading is generated by a mock provider (GPS Spoofing).
     * Works across modern Android (Android 12+ API 31+) and legacy platforms.
     */
    fun isLocationSpoofed(location: Location?): Boolean {
        if (location == null) return false
        return if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            location.isMock
        } else {
            @Suppress("DEPRECATION")
            location.isFromMockProvider
        }
    }

    /**
     * Calculates direct distance in meters between two lat/lng points.
     */
    fun distanceBetween(lat1: Double, lng1: Double, lat2: Double, lng2: Double): Float {
        val result = FloatArray(1)
        Location.distanceBetween(lat1, lng1, lat2, lng2, result)
        return result[0]
    }

    /**
     * Finds the minimum distance from (lat, lng) to any vertex in the coordinate list.
     */
    fun minDistanceToPoints(lat: Double, lng: Double, points: List<LocationCoordinate>): Float {
        if (points.isEmpty()) return Float.MAX_VALUE
        var minDist = Float.MAX_VALUE
        for (pt in points) {
            val d = distanceBetween(lat, lng, pt.latitude, pt.longitude)
            if (d < minDist) {
                minDist = d
            }
        }
        return minDist
    }

    /**
     * Calculates minimum perpendicular distance to any segment of the polygon.
     */
    fun minDistanceToPolygonPerimeter(lat: Double, lng: Double, points: List<LocationCoordinate>): Float {
        if (points.isEmpty()) return Float.MAX_VALUE
        if (points.size < 3) return minDistanceToPoints(lat, lng, points)

        var minDistance = Float.MAX_VALUE
        var j = points.size - 1
        for (i in points.indices) {
            val d = distanceToSegment(lat, lng, points[j].latitude, points[j].longitude, points[i].latitude, points[i].longitude)
            if (d < minDistance) {
                minDistance = d
            }
            j = i
        }
        return minDistance
    }

    private fun distanceToSegment(pLat: Double, pLng: Double, aLat: Double, aLng: Double, bLat: Double, bLng: Double): Float {
        val abDist = distanceBetween(aLat, aLng, bLat, bLng)
        if (abDist == 0f) return distanceBetween(pLat, pLng, aLat, aLng)

        // Project point p onto segment ab
        val apDist = distanceBetween(aLat, aLng, pLat, pLng)
        val bpDist = distanceBetween(bLat, bLng, pLat, pLng)

        // If angle is obtuse, return distance to nearest endpoint
        if (apDist * apDist >= bpDist * bpDist + abDist * abDist) return bpDist
        if (bpDist * bpDist >= apDist * apDist + abDist * abDist) return apDist

        // Perpendicular distance using Heron's formula / triangle height
        val s = (abDist + apDist + bpDist) / 2f
        val area = Math.sqrt(Math.max(0.0, (s * (s - abDist) * (s - apDist) * (s - bpDist)).toDouble())).toFloat()
        return (2f * area) / abDist
    }

    /**
     * Determines whether (lat, lng) is within an active worksite boundary.
     * Polygon: strictly inside polygon OR within pinpoint 10m perimeter buffer.
     * Point: within 35m circular radius.
     */
    fun isCoordinateInsideJob(
        lat: Double,
        lng: Double,
        job: JobItem,
        perimeterBuffer: Float = PINPOINT_PERIMETER_BUFFER_METERS
    ): Boolean {
        if (job.location.isEmpty()) return false
        if (job.siteType.equals("accommodation", ignoreCase = true) || job.isStartingPoint == true) {
            return false
        }

        val points = job.location
        return if (points.size >= 3) {
            if (isPointInPolygon(lat, lng, points)) return true
            minDistanceToPolygonPerimeter(lat, lng, points) <= perimeterBuffer
        } else {
            minDistanceToPoints(lat, lng, points) <= 35f
        }
    }

    /**
     * Returns the active worksite if the worker is inside any assigned job.
     */
    fun findMatchingJob(
        lat: Double,
        lng: Double,
        jobs: List<JobItem>,
        perimeterBuffer: Float = PINPOINT_PERIMETER_BUFFER_METERS
    ): JobItem? {
        for (job in jobs) {
            if (isCoordinateInsideJob(lat, lng, job, perimeterBuffer)) {
                return job
            }
        }
        return null
    }

    /**
     * Determines whether (lat, lng) is within Accommodation/Stay.
     * Uses 25m perimeter buffer for polygons or 60m radius for points to accommodate
     * residential buildings and indoor GPS drift.
     */
    fun isCoordinateInsideAccommodation(lat: Double, lng: Double, acc: AccommodationItem?): Boolean {
        if (acc == null || acc.location.isEmpty()) return false
        val points = acc.location
        return if (points.size >= 3) {
            if (isPointInPolygon(lat, lng, points)) return true
            minDistanceToPolygonPerimeter(lat, lng, points) <= 25f
        } else {
            minDistanceToPoints(lat, lng, points) <= 60f
        }
    }

    /**
     * Returns the minimum distance in meters to the accommodation boundary/center.
     */
    fun getDistanceToAccommodation(lat: Double, lng: Double, acc: AccommodationItem?): Float {
        if (acc == null || acc.location.isEmpty()) return Float.MAX_VALUE
        return minDistanceToPolygonPerimeter(lat, lng, acc.location)
    }

    /**
     * Resolves the worker's assigned accommodation from SharedPreferences cache,
     * with automatic fallback to any accommodation / starting point job configured in CACHED_JOBS_JSON.
     */
    fun getOrResolveAccommodation(context: Context): AccommodationItem? {
        val geoPrefs = context.getSharedPreferences("GeoPrefs", Context.MODE_PRIVATE)
        val json = geoPrefs.getString("CACHED_ACCOMMODATION_JSON", null)
        if (json != null) {
            try {
                val acc = Gson().fromJson(json, AccommodationItem::class.java)
                if (acc != null && acc.location.isNotEmpty()) return acc
            } catch (_: Exception) {}
        }

        // Fallback: Check if accommodation was sent as an item inside jobs
        val jobsJson = geoPrefs.getString("CACHED_JOBS_JSON", null) ?: return null
        return try {
            val type = object : TypeToken<List<JobItem>>() {}.type
            val jobs: List<JobItem> = Gson().fromJson(jobsJson, type) ?: emptyList()
            val accJob = jobs.find { it.siteType.equals("accommodation", ignoreCase = true) || it.isStartingPoint == true }
            if (accJob != null && accJob.location.isNotEmpty()) {
                AccommodationItem(
                    id = accJob.jobId,
                    name = accJob.jobTitle ?: "Assigned Accommodation",
                    location = accJob.location,
                    address = accJob.address ?: ""
                )
            } else null
        } catch (_: Exception) {
            null
        }
    }
}
